name: hafiyyat
description: Steganografi tekniği kullanarak gri görüntüleri renkli görüntülere gizleyen mobil uygulama.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  image: ^4.1.3
  share_plus: ^7.1.0
  permission_handler: ^11.0.1
  flutter_native_splash: ^2.2.8
  async: ^2.12.0
  material_color_utilities: 0.11.1 # flutter_test ile uyumlu
  vector_math: 2.1.4 # flutter_test ile uyumlu
  media_store_plus: ^0.1.3
  shared_preferences: ^2.2.2
  archive: ^4.0.7
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  fake_async: ^1.3.2
  leak_tracker: ^10.0.0 # 11.0.1 çakışıyordu
  leak_tracker_flutter_testing: 3.0.9 # flutter_test ile uyumlu
  lints: ^3.0.0
  vm_service: 14.3.1 # flutter_test ile uyumlu

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon_blank.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_blank.png"

flutter_native_splash:
  color: "#0A192F"
  image: assets/images/app_icon_blank.png
  android_12:
    color: "#0A192F"
    image: assets/images/app_icon_blank.png
    icon_background_color: "#0A192F"
  fullscreen: true
  android: true
  ios: true
